export { authService } from './authService'
export { studentService } from './studentService'
export { preceptorService } from './preceptorService'
export { groupService } from './groupService'
export { hospitalService } from './hospitalService'
export { rotationAssignmentService } from './rotationAssignmentService'
